import { StyleSheet } from "react-native";

export const chatStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5efe3",
  },
  header: {
    marginTop: 14,
    marginBottom: 12,
    paddingHorizontal: 18,
  },
  screenTitle: {
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#8b7355",
    fontWeight: "700",
    marginBottom: 8,
  },
  headerBlock: {
    backgroundColor: "#17324d",
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#12304b",
  },
  headerTitle: {
    color: "#f8fafc",
    fontSize: 24,
    fontWeight: "800",
  },
  headerSubtitle: {
    marginTop: 4,
    color: "#dbe6f0",
    fontSize: 13,
  },
  chatList: {
    flex: 1,
    paddingHorizontal: 18,
  },
  chatContent: {
    paddingBottom: 16,
  },
  messageRow: {
    marginBottom: 12,
  },
  userRow: {
    alignItems: "flex-end",
  },
  assistantRow: {
    alignItems: "flex-start",
  },
  bubble: {
    maxWidth: "88%",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
  },
  userBubble: {
    backgroundColor: "#17324d",
    borderColor: "#17324d",
  },
  assistantBubble: {
    backgroundColor: "#fffdf8",
    borderColor: "#eadfca",
  },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
  },
  userText: {
    color: "#ffffff",
  },
  assistantText: {
    color: "#2b3c4f",
  },
  recCard: {
    marginTop: 10,
    width: "88%",
    backgroundColor: "#fffdf8",
    borderWidth: 1,
    borderColor: "#eadfca",
    borderRadius: 14,
    padding: 12,
  },
  recHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
    gap: 8,
  },
  recTitle: {
    flex: 1,
    color: "#17324d",
    fontSize: 15,
    fontWeight: "700",
  },
  recDiff: {
    backgroundColor: "#f0e6d5",
    color: "#5f4f3a",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  recReason: {
    color: "#5f4f3a",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  topicsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 10,
  },
  topicPill: {
    backgroundColor: "#e8f4f1",
    borderWidth: 1,
    borderColor: "#bfe2db",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  topicText: {
    fontSize: 11,
    color: "#26574f",
    fontWeight: "600",
  },
  recAction: {
    alignSelf: "flex-start",
    borderRadius: 10,
    backgroundColor: "#ff7849",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  recActionText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  composerWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: "#f5efe3",
    borderTopWidth: 1,
    borderTopColor: "#eadfca",
    zIndex: 20,
  },
  composerInner: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  input: {
    flex: 1,
    minHeight: 48,
    maxHeight: 120,
    borderWidth: 1,
    borderColor: "#d2c3a9",
    backgroundColor: "#fffdf8",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#1f2937",
    fontSize: 14,
    textAlignVertical: "top",
  },
  sendButton: {
    height: 48,
    borderRadius: 12,
    paddingHorizontal: 14,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#17324d",
  },
  sendDisabled: {
    backgroundColor: "#8fa1b3",
  },
  sendText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 13,
  },
  loadingRow: {
    alignItems: "flex-start",
    marginBottom: 8,
    paddingHorizontal: 18,
  },
  loadingBubble: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#eadfca",
    backgroundColor: "#fffdf8",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  loadingText: {
    color: "#7b6a53",
    fontSize: 13,
  },
  emptyState: {
    marginTop: 24,
    marginHorizontal: 18,
    backgroundColor: "#fffdf8",
    borderWidth: 1,
    borderColor: "#eadfca",
    borderRadius: 14,
    padding: 16,
  },
  emptyTitle: {
    color: "#17324d",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 6,
  },
  emptyText: {
    color: "#5f4f3a",
    fontSize: 13,
    lineHeight: 19,
  },
});
