import { StyleSheet } from 'react-native';

export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#e8e8e8ff',
    paddingTop: 25,
    paddingBottom: 15,
  },
  headerCard: {
    backgroundColor: 'linear-gradient(135deg, #2721ecff 0%, #2721ecff 100%)',
    backgroundColor: '#2721ecff',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    padding: 20,
    paddingTop:5,
    marginBottom:20,
    marginTop: 10, // Additional margin from top
  },
  headerContent: {
    paddingTop: 10,
  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  greeting: {
    flex: 1,
    marginLeft: 12,
  },
  greetingText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  subText: {
    color: '#E5E7EB',
    fontSize: 14,
    marginTop: 2,
  },
  notificationBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: {
    fontSize: 16,
  },
  streakSection: {
    marginBottom: 20,
  },
  streakInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  streakLabel: {
    color: '#fff',
    fontSize: 16,
  },
  streakDays: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  timerSection: {
    alignItems: 'center',
  },
  timerLabel: {
    color: '#E5E7EB',
    fontSize: 14,
    marginBottom: 12,
  },
  timerContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  timeBox: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    minWidth: 50,
  },
  timeNumber: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  timeLabel: {
    color: '#E5E7EB',
    fontSize: 10,
    marginTop: 2,
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  viewAllText: {
    color: '#8B5CF6',
    fontSize: 14,
    fontWeight: '600',
  },
  contestCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  contestHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  contestIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#2721ecff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contestIconText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  contestInfo: {
    flex: 1,
    marginLeft: 12,
  },
  contestTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  contestPlatform: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 2,
  },
  contestBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FEF2F2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeIcon: {
    fontSize: 16,
  },
  contestDetails: {
    marginBottom: 16,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 14,
    color: '#6B7280',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
  },
  reminderButton: {
    backgroundColor: '#2721ecff',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  reminderText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  statIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  statIconText: {
    fontSize: 16,
  },
  statLabel: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  practiceCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  practiceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  practiceIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ECFDF5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  practiceIconText: {
    fontSize: 18,
  },
  practiceInfo: {
    flex: 1,
    marginLeft: 12,
  },
  practiceLabel: {
    fontSize: 14,
    color: '#6B7280',
  },
  practiceValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1F2937',
    marginTop: 2,
  },
  practiceChange: {
    alignItems: 'flex-end',
  },
  changeLabel: {
    fontSize: 12,
    color: '#6B7280',
  },
  changeValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#10B981',
    marginTop: 2,
  },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#2721ecff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  fabText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  // Practice Dashboard Styles
  practiceSection: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  practiceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  practiceHubIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  practiceHubIconText: {
    color: '#fff',
    fontSize: 16,
  },
  practiceHubTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1F2937',
    flex: 1,
    marginLeft: 12,
  },
  practiceHeaderIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  practiceHeaderIcon: {
    fontSize: 20,
  },
  profileAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#8B5CF6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileAvatarText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  dailyGoalCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  dailyGoalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  dailyGoalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  dailyGoalProgress: {
    fontSize: 14,
    color: '#6B7280',
  },
  dailyGoalDescription: {
    fontSize: 14,
    color: '#6B7280',
    fontStyle: 'italic',
  },
  weekSection: {
    marginBottom: 20,
  },
  weekTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 12,
  },
  weekCalendar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  dayBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  completedDay: {
    backgroundColor: '#10B981',
  },
  currentDay: {
    backgroundColor: '#8B5CF6',
  },
  futureDay: {
    backgroundColor: '#E5E7EB',
  },
  dayText: {
    fontSize: 12,
    fontWeight: '600',
  },
  completedDayText: {
    color: '#fff',
  },
  currentDayText: {
    color: '#fff',
  },
  futureDayText: {
    color: '#9CA3AF',
  },
  difficultyFilter: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
  },
  difficultyChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
  },
  allChip: {
    backgroundColor: '#8B5CF6',
  },
  allChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  difficultyChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
  },
  dailyChallengeCard: {
    backgroundColor: '#8B5CF6',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
  },
  challengeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  challengeTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  challengeDifficulty: {
    fontSize: 12,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  challengeProblemTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
  },
  challengeDescription: {
    fontSize: 14,
    color: '#E5E7EB',
    marginBottom: 16,
    lineHeight: 20,
  },
  challengeFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  challengeStats: {
    flexDirection: 'row',
    gap: 16,
  },
  challengeStat: {
    fontSize: 12,
    color: '#E5E7EB',
  },
  startButton: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 12,
  },
  startButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#8B5CF6',
  },
  practiceItem: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  practiceItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  practiceItemTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  practiceItemDifficulty: {
    fontSize: 16,
  },
  practiceItemSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 12,
  },
  progressBar: {
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 2,
  },
  topicsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  topicCard: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  circularProgress: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  progressPercentage: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  topicTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1F2937',
    textAlign: 'center',
    marginBottom: 4,
  },
  topicSubtitle: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
  },
});