import { StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5efe3',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  card: {
    width: '100%',
    backgroundColor: '#fffdf8',
    borderRadius: 18,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#eadfca',
    shadowColor: '#7c5f3b',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  iconContainer: {
    marginBottom: 16,
  },
  iconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#17324d',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconText: {
    fontSize: 28,
    color: '#fff',
    fontWeight: 'bold',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#17324d',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#7b6a53',
    marginBottom: 24,
  },
  input: {
    width: '100%',
    backgroundColor: '#f6efe1',
    color: '#17324d',
    padding: 12,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#eadfca',
  },
  passwordContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    position: 'relative',
  },
  eyeButton: {
    position: 'absolute',
    right: 12,
    padding: 4,
  },
  eye: {
    fontSize: 18,
    color: '#17324d',
  },
  forgotContainer: {
    width: '100%',
    alignItems: 'flex-end',
    marginBottom: 16,
  },
  forgotText: {
    color: '#0f766e',
    fontWeight: '500',
  },
  signInButton: {
    width: '100%',
    backgroundColor: '#17324d',
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  signInText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
    width: '100%',
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: '#d8cab1',
  },
  orText: {
    color: '#8b7355',
    marginHorizontal: 8,
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#eadfca',
  },
  socialImage: {
    width: 24,
    height: 24,
    marginRight: 12,
  },
  socialText: {
    color: '#17324d',
    fontWeight: '500',
  },
  signupContainer: {
    flexDirection: 'row',
    marginTop: 8,
  },
  signupText: {
    color: '#7b6a53',
  },
  signupLink: {
    color: '#0f766e',
    fontWeight: '500',
  },
});
