import { StyleSheet } from 'react-native';

export const problemsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5efe3',
  },
  header: {
    backgroundColor: '#fffdf8',
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#eadfca',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#7b6a53',
    textAlign: 'center',
    marginBottom: 20,
    letterSpacing: 1,
  },
  filterContainer: {
    marginBottom: 16,
  },
  filterDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f6efe1',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#eadfca',
  },
  filterIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  filterText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#17324d',
  },
  dropdownIcon: {
    fontSize: 14,
    color: '#7b6a53',
    marginRight: 8,
  },
  sortIcon: {
    fontSize: 16,
    color: '#7b6a53',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f6efe1',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#eadfca',
  },
  searchIcon: {
    fontSize: 16,
    marginRight: 8,
    color: '#7b6a53',
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#17324d',
  },
  problemsList: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  problemCard: {
    backgroundColor: '#fffdf8',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#7c5f3b',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#eadfca',
  },
  problemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  problemTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#17324d',
    flex: 1,
    marginRight: 12,
  },
  completionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  completionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#7b6a53',
  },
  completionIcon: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  completedIcon: {
    fontSize: 16,
  },
  incompleteCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#c7b99f',
  },
  problemMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  difficultyBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  difficultyText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  platformText: {
    fontSize: 14,
    color: '#7b6a53',
    fontWeight: '500',
  },
  topicsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  topicTag: {
    backgroundColor: '#f6efe1',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  topicText: {
    fontSize: 12,
    color: '#7b6a53',
    fontWeight: '500',
  },
});