import { StyleSheet } from 'react-native';

export const problemDetailsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5efe3',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: '#7b6a53',
  },
  header: {
    backgroundColor: '#fffdf8',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: 50,
    borderBottomWidth: 1,
    borderBottomColor: '#eadfca',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f6efe1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    fontSize: 18,
    color: '#17324d',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#17324d',
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f6efe1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuIcon: {
    fontSize: 18,
    color: '#17324d',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  titleSection: {
    backgroundColor: '#fffdf8',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#7c5f3b',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#eadfca',
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  problemTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#17324d',
    flex: 1,
    marginRight: 12,
  },
  likeButton: {
    padding: 4,
  },
  likeIcon: {
    fontSize: 24,
    color: '#c7b99f',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  difficultyBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  difficultyText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  platformText: {
    fontSize: 14,
    color: '#7b6a53',
    fontWeight: '500',
  },
  timerSection: {
    backgroundColor: '#fffdf8',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#7c5f3b',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#eadfca',
  },
  timerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  timerIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  timerLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#17324d',
  },
  timerDisplay: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#17324d',
    textAlign: 'center',
    marginBottom: 16,
    fontFamily: 'monospace',
  },
  timerControls: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
  },
  timerButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    minWidth: 60,
    alignItems: 'center',
  },
  startButton: {
    backgroundColor: '#17324d',
  },
  startButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  pauseButton: {
    backgroundColor: '#7b6a53',
  },
  pauseButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  resetButton: {
    backgroundColor: '#ff7849',
  },
  resetButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  topicsSection: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  topicTag: {
    backgroundColor: '#f6efe1',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  topicText: {
    fontSize: 12,
    color: '#7b6a53',
    fontWeight: '500',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#fffdf8',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
    shadowColor: '#7c5f3b',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#eadfca',
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 8,
  },
  activeTab: {
    backgroundColor: '#17324d',
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#7b6a53',
  },
  activeTabText: {
    color: '#FFFFFF',
  },
  tabContent: {
    backgroundColor: '#fffdf8',
    borderRadius: 16,
    padding: 20,
    marginBottom: 30,
    shadowColor: '#7c5f3b',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#eadfca',
  },
  descriptionText: {
    fontSize: 16,
    color: '#17324d',
    lineHeight: 24,
  },
  exampleContainer: {
    marginBottom: 16,
    padding: 16,
    backgroundColor: '#f6efe1',
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#0f766e',
  },
  exampleTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#17324d',
    marginBottom: 8,
  },
  exampleText: {
    fontSize: 14,
    color: '#17324d',
    marginBottom: 4,
    fontFamily: 'monospace',
  },
  constraintText: {
    fontSize: 14,
    color: '#17324d',
    marginBottom: 8,
    lineHeight: 20,
  },
  hintText: {
    fontSize: 14,
    color: '#17324d',
    marginBottom: 12,
    lineHeight: 20,
    paddingLeft: 8,
  },
  bottomActions: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    right: 20,
    backgroundColor: '#fffdf8',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#7c5f3b',
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  startSolvingButton: {
    flex: 1,
    backgroundColor: '#17324d',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    marginRight: 12,
  },
  startSolvingIcon: {
    color: '#FFFFFF',
    fontSize: 16,
    marginRight: 8,
  },
  startSolvingText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f6efe1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtonIcon: {
    fontSize: 18,
    color: '#7b6a53',
  },
});